// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  description: dynamic(() => import("./Description")),
  gallery: dynamic(() => import("./Gallery")),
  hero_media: dynamic(() => import("./HeroMedia")),
  hero_project: dynamic(() => import("./HeroProject")),
  image: dynamic(() => import("./Image")),
  project_credits: dynamic(() => import("./ProjectCredits")),
  teaser_text: dynamic(() => import("./TeaserText")),
};
